In [1]:
import numpy as np

In [10]:
a=np.array([1,2,3],dtype='int16')

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([[3,4,5,],[4,5,6]])

In [5]:
b

array([[3, 4, 5],
       [4, 5, 6]])

In [6]:
b.shape

(2, 3)

In [7]:
b.dtype

dtype('int64')

In [8]:
a.dtype

dtype('int64')

In [11]:
a.dtype

dtype('int16')

In [12]:
b.itemsize

8

In [13]:

#get total size
a.nbytes

6

In [15]:
a

array([1, 2, 3], dtype=int16)

In [16]:
b

array([[3, 4, 5],
       [4, 5, 6]])

In [17]:
b[1,1]

np.int64(5)

In [19]:
a = np.array([[2,4,4,5,4],[4,6,7,2,8],[4,2,7,8,13]])

In [20]:
a[2,-1]

np.int64(13)

In [21]:
a[1,2:5]

array([7, 2, 8])

In [22]:
a[:,2]=9

In [23]:
a

array([[ 2,  4,  9,  5,  4],
       [ 4,  6,  9,  2,  8],
       [ 4,  2,  9,  8, 13]])

In [26]:
b=np.round(10*np.random.rand(3,2,2))

In [27]:
b

array([[[2., 4.],
        [5., 9.]],

       [[2., 8.],
        [1., 7.]],

       [[7., 5.],
        [3., 8.]]])

In [28]:
b[0,1,1]

np.float64(9.0)

In [29]:
b[:,1,:]

array([[5., 9.],
       [1., 7.],
       [3., 8.]])

In [31]:
b[:,1,0]

array([5., 1., 3.])

In [32]:
b[0,:]

array([[2., 4.],
       [5., 9.]])

In [33]:
b[0,:1]

array([[2., 4.]])

In [34]:
b[0,:,1]

array([4., 9.])

In [35]:
b[0,0,0]

np.float64(2.0)

In [36]:
b[0,:,0]

array([2., 5.])

In [39]:
b[:,1,:]=[[9,9]]

In [40]:
b

array([[[2., 4.],
        [9., 9.]],

       [[2., 8.],
        [9., 9.]],

       [[7., 5.],
        [9., 9.]]])

In [41]:
#all 0s matrix
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [42]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.full((2,3),44) #any other number

array([[44, 44, 44],
       [44, 44, 44]])

In [45]:
#any other number(full like)
np.full(a.shape,9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [46]:
a

array([[ 2,  4,  9,  5,  4],
       [ 4,  6,  9,  2,  8],
       [ 4,  2,  9,  8, 13]])

In [48]:
np.full(np.shape(3),7)

array(7)

In [52]:
np.full(np.random.randint(3,5),4)

array([4, 4, 4])

In [53]:
np.full(np.matrix(2,3),5)

TypeError: Cannot interpret '3' as a data type

In [54]:
np.random.random_sample(a.shape)

array([[0.57966045, 0.2163267 , 0.1212889 , 0.47429498, 0.92923697],
       [0.72917155, 0.05366991, 0.37031348, 0.78864066, 0.54829799],
       [0.89300189, 0.9948112 , 0.49350213, 0.90954761, 0.26531275]])

In [ ]:
np.random.rand(4,2) 

array([[0.96616199, 0.78839851],
       [0.62961411, 0.65546435],
       [0.91812309, 0.48160838],
       [0.11269353, 0.80170232]])

In [60]:
np.random.randint(4,7,size=(3,3)) #random integer values

array([[6, 4, 4],
       [5, 6, 6],
       [5, 4, 6]], dtype=int32)

In [62]:
np.random.randint(7,size=(3,3))

array([[0, 4, 3],
       [1, 0, 3],
       [0, 1, 2]], dtype=int32)

In [63]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
import numpy as np
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [5]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [7]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,4,axis=0)
print(r1)

[1 1 1 1 2 2 2 2 3 3 3 3]


In [8]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [9]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [3]:
import numpy as np
output = np.ones((5,5))
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
z = np.zeros((3,3))
z[1,1 ] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [5]:
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
output[1:4,:]

array([[1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.]])

In [7]:
a = np.array([1,2,3])
b =a

In [8]:
b[0]

np.int64(1)

In [9]:
b[0]=9

In [10]:
a

array([9, 2, 3])

In [11]:
b = a.copy()

In [12]:
b

array([9, 2, 3])

In [13]:
b[0]=100

In [14]:
b

array([100,   2,   3])

In [15]:
a

array([9, 2, 3])

Mathmetics

In [16]:
a = np.array([1,2,3,4])


In [17]:
a

array([1, 2, 3, 4])

In [18]:
a+2

array([3, 4, 5, 6])

In [19]:
a*2

array([2, 4, 6, 8])

In [20]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [21]:
b= np.array([3,0,4,5])

In [22]:
a+b

array([4, 2, 7, 9])

In [27]:
a*b

array([ 3,  0, 12, 20])

In [23]:
a**2

array([ 1,  4,  9, 16])

In [24]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [25]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [26]:
####Linear algebra

In [30]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
b = np.full((3,2),2)

In [32]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [35]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [38]:
np.linalg.det(np.identity(3))

np.float64(1.0)

In [40]:
import numpy.linalg as npl

In [43]:
a=np.full((3,3),4)
print(a)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [44]:
npl.det(a)

np.float64(0.0)

In [45]:
npl.trace(a)

np.int64(12)

Statistics

In [54]:
stats = np.array([[1,2,14],[9,4,5]])
stats

array([[ 1,  2, 14],
       [ 9,  4,  5]])

In [47]:
np.min(stats)

np.int64(1)

In [56]:
np.min(stats,axis=1)

array([1, 4])

In [57]:
np.max(stats)

np.int64(14)

In [55]:
np.max(stats,axis=0)

array([ 9,  4, 14])

In [59]:
np.max(stats,axis=1)

array([14,  9])

In [60]:
#rearanging araays

In [62]:
before = np.array([[1,2,14],[9,4,5]])
print(before)

after = before.reshape((3,2))
after

[[ 1  2 14]
 [ 9  4  5]]


array([[ 1,  2],
       [14,  9],
       [ 4,  5]])

In [65]:
#verrtically staking vector
v1 = np.array([1,2,3,4])
v2 = np.array([3,5,7,8])


In [68]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [3, 5, 7, 8]])

In [ ]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 3, 5, 7, 8])

In [70]:
np.vstack([v2,v1,v1,v2])

array([[3, 5, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [3, 5, 7, 8]])

In [71]:
# load data from file
#np.genfromtxt('data.txt,delimitar=',')

Boolen masking and advanced indexing

In [73]:
#you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,4,8]]

array([2, 5, 9])